
server:
  port: 6001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 1024

spring:
  application:
    name: company-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.250:3306/worker-dev?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: mysql_xMYB44
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: DataSourceHikariCP
      auto-commit: true
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.250:8848
        username: nacos
        password: nacos